export const LOGIN_PATH_NAME = "LOGIN"

export const CALENDAR_PATH_NAME = "CALENDAR"

export const CLIENT_PATH_NAME = "CLIENT"

export const CHECK_LIST_PATH_NAME = "CHECK LIST"

export const REPORT_PATH_NAME = "REPORT"

export const URGENCIES_PATH_NAME = "URGENCIES"

export const VACATIONS_PATH_NAME = "VACATIONS"